# Generated by Django 4.1.7 on 2023-03-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_donormodel_phonenumber_alter_medmodel_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medmodel',
            name='exp_date_ocr',
            field=models.CharField(default='No Ocr value detected', max_length=255),
        ),
    ]
