# Generated by Django 5.2.5 on 2026-01-06 04:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EligibilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rule_type', models.CharField(choices=[('EXPIRY_DATE', 'Expiry Date Validation'), ('CATEGORY', 'Category Restriction'), ('PACKAGING', 'Packaging Integrity'), ('QUANTITY', 'Quantity Limits'), ('DOCUMENTATION', 'Documentation Requirements'), ('CUSTOM', 'Custom Rule')], max_length=50)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_blocking', models.BooleanField(default=True, help_text='If True, failure blocks acceptance')),
                ('min_shelf_life_days', models.IntegerField(blank=True, help_text='Minimum days until expiry', null=True)),
                ('allowed_categories', models.JSONField(blank=True, help_text='List of allowed categories', null=True)),
                ('required_packaging_status', models.JSONField(blank=True, null=True)),
                ('min_quantity', models.IntegerField(blank=True, null=True)),
                ('max_quantity', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['rule_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReasonCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Short code identifier (e.g., EXP-001)', max_length=20, unique=True)),
                ('decision_type', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('REVIEW', 'Needs Review'), ('REJECTED', 'Rejected'), ('ANY', 'Applicable to Any')], max_length=20)),
                ('description', models.TextField(help_text='Full description of this reason code')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supply_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('item_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('PPE', 'Personal Protective Equipment'), ('SURGICAL', 'Surgical Supplies'), ('DIAGNOSTIC', 'Diagnostic Equipment'), ('WOUND_CARE', 'Wound Care'), ('EQUIPMENT', 'Medical Equipment'), ('OTHER_SUPPLIES', 'Other Medical Supplies')], max_length=50)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit', models.CharField(choices=[('pieces', 'Pieces'), ('boxes', 'Boxes'), ('packs', 'Packs'), ('units', 'Units'), ('sets', 'Sets')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('expiry_date', models.DateField()),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('packaging_status', models.CharField(choices=[('SEALED_UNOPENED', 'Sealed & Unopened'), ('OPENED_INTACT', 'Opened but Intact'), ('MINOR_DAMAGE', 'Minor Damage'), ('SIGNIFICANT_DAMAGE', 'Significant Damage')], max_length=50)),
                ('storage_conditions', models.CharField(choices=[('CONTROLLED', 'Controlled Environment'), ('ROOM_TEMP', 'Room Temperature'), ('REFRIGERATED', 'Refrigerated'), ('UNKNOWN', 'Unknown')], max_length=50)),
                ('submitted_date', models.DateTimeField(auto_now_add=True)),
                ('decision_status', models.CharField(choices=[('PENDING_INITIAL', 'Pending Initial Review'), ('PENDING_FINAL', 'Pending Final Approval'), ('ACCEPTED', 'Accepted for Redistribution'), ('NEEDS_REVIEW', 'Needs Additional Review'), ('REJECTED', 'Rejected')], default='PENDING_INITIAL', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custody_hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_supplies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Supplies',
                'ordering': ['-submitted_date'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('PHOTO_PACKAGING', 'Photo - Packaging'), ('PHOTO_LABEL', 'Photo - Label/Expiry'), ('PHOTO_PRODUCT', 'Photo - Product'), ('DOCUMENT_COA', 'Certificate of Analysis'), ('DOCUMENT_INVOICE', 'Purchase Invoice'), ('DOCUMENT_OTHER', 'Other Documentation')], max_length=50)),
                ('file', models.FileField(max_length=500, upload_to='evidence/%Y/%m/')),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_set', to='decision_system.supply')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('ACCEPTED', 'Accepted for Redistribution'), ('REVIEW', 'Needs Additional Review'), ('REJECTED', 'Rejected')], max_length=20)),
                ('decision_level', models.CharField(choices=[('INITIAL', 'Initial Review'), ('FINAL', 'Final Approval'), ('OVERRIDE', 'Administrative Override')], max_length=20)),
                ('justification', models.TextField(help_text='Detailed explanation for this decision')),
                ('notes', models.TextField(blank=True, help_text='Additional internal notes')),
                ('decision_date', models.DateTimeField(auto_now_add=True)),
                ('eligibility_passed', models.BooleanField(help_text='Did the supply pass automated eligibility checks?')),
                ('eligibility_details', models.JSONField(blank=True, help_text='Snapshot of eligibility check results', null=True)),
                ('decision_hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('is_superseded', models.BooleanField(default=False, help_text='True if a newer decision exists')),
                ('decided_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions_made', to=settings.AUTH_USER_MODEL)),
                ('reason_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='decision_system.reasoncode')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decision_set', to='decision_system.supply')),
            ],
            options={
                'ordering': ['-decision_date'],
                'permissions': [('can_make_initial_decision', 'Can make initial review decisions'), ('can_make_final_decision', 'Can make final approval decisions'), ('can_override_decision', 'Can override previous decisions')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SUPPLY_SUBMITTED', 'Supply Submitted'), ('EVIDENCE_UPLOADED', 'Evidence Uploaded'), ('DECISION_MADE', 'Decision Made'), ('STATUS_CHANGED', 'Status Changed'), ('RULE_MODIFIED', 'Eligibility Rule Modified'), ('EXPORT_GENERATED', 'Audit Export Generated')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='decision_system.decision')),
                ('supply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='decision_system.supply')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='decision_sy_timesta_a74bba_idx'), models.Index(fields=['action', '-timestamp'], name='decision_sy_action_d88561_idx'), models.Index(fields=['user', '-timestamp'], name='decision_sy_user_id_970117_idx')],
            },
        ),
    ]
