# Generated by Django 5.2.5 on 2026-04-06 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='decision',
            options={'ordering': ['-decision_date']},
        ),
        migrations.RemoveField(
            model_name='decision',
            name='decision_hash',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='file_hash',
        ),
        migrations.RemoveField(
            model_name='supply',
            name='custody_hash',
        ),
        migrations.AlterField(
            model_name='decision',
            name='is_superseded',
            field=models.BooleanField(default=False),
        ),
    ]
